# Generated by Django 5.1.6 on 2025-02-23 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='current_insect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.insect'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='current_plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.plant'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.shopitem'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
