# Generated by Django 5.1.6 on 2025-02-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_level', models.IntegerField(default=0)),
                ('growth', models.FloatField(default=0.0)),
                ('points', models.IntegerField(default=0)),
                ('spins', models.IntegerField(default=0)),
                ('plant', models.CharField(default='leafy', max_length=32)),
                ('snail', models.BooleanField(default=False)),
            ],
        ),
    ]
