# Generated by Django 5.1.6 on 2025-02-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
        ('game', '0003_populate_insects'),
    ]

    operations = [
    ]
