# Generated by Django 5.1.6 on 2025-02-23 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_merge_0002_initial_0003_populate_insects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShopItem',
        ),
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
