# Generated by Django 5.1.6 on 2025-03-08 20:14

from django.db import migrations


def populate_prizes(apps, schema_editor):
    Prize = apps.get_model("game", "Prize")

    # Prize data
    prizes = [
        {"value": 0,    "option": "🎁 No Reward",   "weight": 0.15, "style": {"backgroundColor": "red", "color": "white"}},
        {"value": 50,   "option": "🔥 50 Points",   "weight": 0.35, "style": {"backgroundColor": "black", "color": "white"}},
        {"value": 100,  "option": "🌟 100 Points",  "weight": 0.30, "style": {"backgroundColor": "red", "color": "white"}},
        {"value": 200,  "option": "💎 200 Points",  "weight": 0.15, "style": {"backgroundColor": "black", "color": "white"}},
        {"value": 500,  "option": "☘️ 500 Points",  "weight": 0.40, "style": {"backgroundColor": "red", "color": "white"}},
        {"value": 1000, "option": "🏆 1000 Points", "weight": 0.10, "style": {"backgroundColor": "black", "color": "white"}},
    ]

    # Populate only if empty
    if not Prize.objects.exists():
        for prize_data in prizes:
            Prize.objects.create(**prize_data)

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_update_images'),
    ]

    operations = [
        migrations.RunPython(populate_prizes),
    ]
