# Generated by Django 5.1.6 on 2025-02-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_update_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='lifetime_points',
            field=models.IntegerField(default=0),
        ),
    ]
