# Generated by Django 5.1.6 on 2025-02-23 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_useritem_item_remove_useritem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='current_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.plant'),
        ),
    ]
