# Generated by Django 5.1.6 on 2025-02-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gameprofile_lifetime_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameprofile',
            old_name='plant_growth',
            new_name='tree_growth',
        ),
        migrations.RenameField(
            model_name='gameprofile',
            old_name='plant_level',
            new_name='tree_level',
        ),
    ]
