# Generated by Django 5.1.6 on 2025-02-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_gameprofile_current_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='insect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='insects/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
