# Generated by Django 5.1.6 on 2025-03-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_create_initial_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='last_insect_spawn',
        ),
    ]
