# Generated by Django 5.1.6 on 2025-02-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_insect_image_plant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insect',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
    ]
