# Generated by Django 5.1.6 on 2025-02-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_insect_image_remove_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='insect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='insects/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
