# Generated by Django 5.1.6 on 2025-03-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_shopitem_useritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='spins_remaining',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='spins',
            field=models.IntegerField(default=0),
        ),
    ]
