# Generated by Django 5.1.6 on 2025-03-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_item_stock_item_image_item_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Item-specific parameters (e.g. growth_amount, spawn_chance)'),
        ),
        migrations.AlterField(
            model_name='itemeffect',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Effect-specific parameters (e.g. growth_amount, points, chances)'),
        ),
    ]
