# Generated by Django 5.1.6 on 2025-03-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_gameprofile_spins_remaining_gameprofile_spins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insect',
            name='image',
            field=models.ImageField(null=True, upload_to='insects/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(null=True, upload_to='plants/'),
        ),
    ]
