# Generated by Django 5.1.6 on 2025-03-08 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_insect_image_alter_plant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('option', models.CharField(max_length=32)),
                ('weight', models.FloatField()),
                ('style', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='current_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.plant'),
        ),
    ]
