# Generated by Django 5.1.6 on 2025-03-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_populate_prizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShopItem',
        ),
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
