# Generated by Django 5.1.6 on 2025-03-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_populate_prizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='current_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='last_collected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
