# Generated by Django 5.1.6 on 2025-03-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_item_parameters_alter_itemeffect_parameters'),
        ('game', '0013_gameprofile_current_day_gameprofile_last_collected_and_more'),
    ]

    operations = [
    ]
