# Generated by Django 5.1.7 on 2025-03-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_update_plant_insect_images'),
        ('game', '0016_update_and_finalize_image_fields'),
    ]

    operations = [
    ]
