# Generated by Django 5.1.7 on 2025-03-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_dailyrewardconfig'),
        ('game', '0017_merge_20250321_1652'),
    ]

    operations = [
    ]
