# Generated by Django 5.1.7 on 2025-03-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_merge_0015_dailyrewardconfig_0017_merge_20250321_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insect',
            name='image',
            field=models.CharField(help_text='Path to the insect image in static files', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(help_text='Path to the item image in static files', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.CharField(help_text='Path to the plant image in static files', max_length=100),
        ),
    ]
