# Generated by Django 5.1.6 on 2025-03-07 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrcodes.qrcode'),
        ),
    ]
