# Generated by Django 5.1.6 on 2025-02-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badge',
            field=models.CharField(blank=True, default='🌱', max_length=10),
        ),
    ]
