# Generated by Django 5.1.7 on 2025-03-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(default='profile_pics/default.png', help_text='Path to the profile picture in static files', max_length=100),
        ),
    ]
