# Generated by Django 5.1.6 on 2025-02-23 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_snail',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lifetime_points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='points_balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tree_growth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tree_level',
        ),
    ]
