# Generated by Django 5.1.6 on 2025-02-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='badge',
        ),
    ]
