# Generated by Django 5.1.7 on 2025-03-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.png', help_text='Path to the profile picture in static files', upload_to='profile_pics/'),
        ),
    ]
