# Generated by Django 5.1.6 on 2025-02-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_profile_picture'),
        ('users', '0004_alter_userprofile_id'),
    ]

    operations = [
    ]
